### ISSUE TITLE
Twitter share link is broken

### ISSUE THREAD

**Issue by peterhershey** [ianbusko/the-noted-project#44]
Twitter share link at the end of each story just opens up a blank tweet.

**Comment by ianbusko** [comment]
Maybe your content isn't interesting.

**Comment by ianbusko** [comment]
This should be fixed in the next publish. @peterhershey

**Comment by peterhershey** [comment]
@ianbusko Not quite fixed...

The tweets have something funky going on:
"The%20Noted%20Project.%20Stories%20of%20musicians%20from%20the%20Thai-Burma%20border. https://thenotedproject.org"
"Share%20Eh%20Klo%20Moo's%20Story https://roasted-feather.surge.sh/story/eh-klo-moo"

Otherwise, looks good.
